apiVersion: v1
kind: Service
metadata: 
    name: {{.Release.Namespace}}
    namespace: {{.Release.Namespace}}
spec: 
    type: LoadBalancer
    selector: 
        app: {{.Release.Namespace}}
    ports: 
    - name: svc-port
      port: {{.Values.containerPort}}
      targetPort: app-port
      protocol: TCP
